networks:
  default:
    external: true
    name: roboshop

services:
  mongodb:
    image: mongodb:1
    container_name: mongodb

  catalogue:
    image: catalogue:1
    container_name: catalogue
    depends_on:
    - mongodb


  web:
    image: web:1
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue

  redis:
    image: redis

  user:
    image: user:1
    container_name: user
    depends_on:
    - redis
    - mongodb

  cart:
    image: cart:1
    container_name: cart
    depends_on:
    - redis
    -catalogue